apiVersion: v1
kind: Pod

metadata:
  name: relayrunner
  labels:
    app: relayrunner

spec:
  containers:
  - name: app

    image: johee/relayrunner:nginx
    imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: relayrunner
  labels:
    app: relayrunner
spec:
  type: NodePort
  selector:
    app: relayrunner
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
